# This is a basic workflow to help you get started with Actions
name: 'Check Pull Request'

on: pull_request

jobs:

  # This tutorial shows how to use 'github-script' as https://github.com/actions/github-script
  tutorial:
    runs-on: ubuntu-latest
    # Remove the default runs-on and uncomment the below line to use self-hosted runner
    # runs-on: self-hosted

    steps:
      # Runs a single command using the runners shell
      - run: echo Hello, world!

      # Commnet on a pull request
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Welcome'
            })

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
