# This is a basic workflow to help you get started with Actions
name: 'Check Pull Request'

on: pull_request

jobs:
  # FIXME This workflow
  fixme:
    runs-on: ubuntu-latest
    # Remove the default runs-on and uncomment the below line to use self-hosted runner
    # runs-on: self-hosted

    steps:
      # Runs a single command using the runners shell
      - run: echo Hello, world!

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
