# This is a basic workflow to help you get started with Actions
name: 'Check Pull Request'

on: pull_request

jobs:
  tutorial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const id = '378e7f8c01b32f424459543ab310261e'
            const remote_filename = 'sample.html'
            const local_filename = 'A.html'

            var resp = await github.gists.get({ gist_id: id })

            if ( resp.status != 200 )
            {
              console.log(resp)
              throw 'Fail'
            }

            if ( !(remote_filename in resp.data.files) )
            {
              throw 'File not found'
            }
            console.log(resp.data.files[remote_filename])

            const fs = require('fs');
            fs.writeFileSync(local_filename, resp.data.files[remote_filename].content)
          github-token: ${{ secrets.GIST_TOKEN }}
      - run: cat A.html
